
CREATE TABLE MARCA (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY, -- Id autonumérico
    NOMBRE VARCHAR(20) NOT NULL,
    FECHA_FUNDACION DATE,
    LOCALIZACION VARCHAR(20) NOT NULL,
    FUNDADOR VARCHAR(20) NOT NULL,
    IMAGEN VARCHAR(30),
    CONSTRAINT ID_MARCA_PK PRIMARY KEY (ID)
);

CREATE TABLE MOVIL (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY, -- Id autonumérico
    MARCA INTEGER,
    NOMBRE VARCHAR(20) NOT NULL,
    MODELO VARCHAR(10) NOT NULL,
    CAPACIDAD VARCHAR(10) NOT NULL,
    ANCHO VARCHAR(10) NOT NULL,
    ALTO VARCHAR(10) NOT NULL,
    GROSOR VARCHAR(10) NOT NULL,
    PESO VARCHAR(10) NOT NULL,
    CHIP VARCHAR(40) NOT NULL,
    CAMARAS CHAR(1),
    PANTALLA VARCHAR(10) NOT NULL,
    SISTEMA_OPERATIVO VARCHAR(10) NOT NULL,
    FECHA_SALIDA DATE,
    PRECIO VARCHAR(10) NOT NULL,
    CINCO_G BOOLEAN,
    CONSTRAINT ID_MOVIL_PK PRIMARY KEY (ID),
    CONSTRAINT PROV_MARCA_FK FOREIGN KEY (MARCA) REFERENCES MARCA (ID)
);

